### ISSUE TITLE
As an Agency I want to enable two-factor/Multifactor authentication for my user accounts

### ISSUE THREAD

**Issue by pandaskii** [govCMS/govCMS8-core#12]
Modules on the radar:

- Two-factor Authentication (TFA) https://www.drupal.org/project/tfa

**Comment by pandaskii** [comment]
TFA module is a little bit buggy at the current stage. 

https://www.drupal.org/forum/support/post-installation/2016-10-18/how-do-i-enable-tfa-in-drupal-8

https://www.drupal.org/project/issues/tfa?text=&status=Open&priorities=All&categories=All&version=8.x&component=All

**Comment by tobybellwood** [comment]
This issue was moved to govCMS/govCMS8#1
