### ISSUE TITLE
Installing the site under ./web instead of ./docroot

### ISSUE THREAD

**Issue by tc-mikerichardson** [govCMS/govCMS8-core#14]
Hello!

I'm trying to get a new govCMS 8 project up and running and I'm hitting a snag with the semantics of where the web root should be. All our internal tooling (mainly Docker images and a Vagrant box) expects the web root be in /web, but Composer insists on putting everything in /docroot. 

I was wondering if there's any install method that enables me to specify that I want things in /web, without breaking the ability to pull down future releases/patches. 

Using the convenience installer (`composer create project`) defaults to /docroot. I have tried editing the paths in composer.json in this repo (https://github.com/govCMS/govCMS8-core/blob/8.4.x/composer.json) and running composer directly but it fails in a few different ways (the latest is that it gets into a loop trying to install phantomjs. 

Please let me know if this is something that should be possible, or if the presence of /docroot is too embedded? 

Thanks!
Mike

**Comment by srowlands** [comment]
You could add a [script](https://getcomposer.org/doc/articles/scripts.md) to your `composer.json` that symlinked ./web to ./docroot.

Should do the trick, much easier than trying to fight against the docroot standard.

**Comment by tc-mikerichardson** [comment]
Thanks for the tip! It would probably work, but we'd have to do that everywhere. 

The more I think about this, the more I'm coming to accept that properly adopting "the docroot standard" might be the smartest, albeit more painful, solution to this problem. 

Thanks again @srowlands
