### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by imperator99** [govCMS/govCMS8-core#2]
Hi,
When trying to install, I got an error concerning Doctrine:

`TypeError: Return value of Doctrine\Common\Annotations\AnnotationRegistry::reset() must be an instance of Doctrine\Common\Annotations\void, none returned in Doctrine\Common\Annotations\AnnotationRegistry::reset() (line 55 of /Applications/MAMP/htdocs/***/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php).`

I was able to resolve this by increasing my PHP version to 7.1 which Doctrine now requires. See [this issue](https://stackoverflow.com/questions/45337962/doctrine2-update-caused-annotationregistry-registerloader-error-in-zend-framewor) for further information.

Either the installation instructions need to be amended to require PHP 7.1 or the relevant composer.json updated to require a specific version of Doctrine not require PHP 7.1.

Cheers,
Jesse.

**Comment by pandaskii** [comment]
Hi @imperator99 

Can you kindly pass your PHP env details?  and steps to reproduce the issue if possible

thanks, Joseph

**Comment by imperator99** [comment]
Hi @pandaskii,

No worries. I'm using MAMP Pro with PHP 7.0.22 as the default PHP version.

Steps to reproduce:

1.  Installed Drupal using the instructions provided in the GovCMS 8 repository, ie with `composer create-project --stability dev --no-interaction govcms/govcms8 au.gov.dta.dev`
2. Ran `composer update`
3. Added the new docroot as a host in MAMP Pro using the default PHP 7.0.22
4. Set up databases using phpMySQL (though this isn't really necessary to replicate).
5. Opening the site shows the message as described in the issue.
6. Switching the PHP version to 7.1.8 allows the site to install properly.

Cheers,
Jesse.

**Comment by pandaskii** [comment]
thanks @imperator99

I have tried to follow the steps with same PHP version in MAMP as yours but couldn't hit the same error. @invisigoth is helping on his machine and I am going to write automation testing to see if we can trigger it.

Packages version after step 2:
[packages.txt](https://github.com/govCMS/govCMS8-core/files/1370043/packages.txt)

Install:
<img width="1206" alt="screen shot 2017-10-10 at 10 14 36 am" src="https://user-images.githubusercontent.com/1326673/31362394-f8bf0b8e-ada3-11e7-80e3-f01ca1fc21c7.png">

<img width="1198" alt="screen shot 2017-10-10 at 10 25 21 am" src="https://user-images.githubusercontent.com/1326673/31362655-5d5d799e-ada5-11e7-9ec2-50d67e19ddee.png">

**Comment by imperator99** [comment]
Okay cool. If there's any other details I can give you about the environment specifically let me know.
Cheers,
Jesse.

**Comment by invisigoth** [comment]
Hi imperator99,

I have tested this on two separately machines running MAMP 4.2.1 (9431).  PHP is set to 7.0.22 for both CLI and web server. I was able to successfully install govCMS following the exact step as you've described above.

Cold you please check which PHP you are using for CLI? For example, just run
`which php`

**Comment by imperator99** [comment]
Running `which php` gives `/usr/local/bin/php'.

**Comment by invisigoth** [comment]
Hi imperator99
That appears to be the OSX default php binary. Could you please try using the PHP shipped with MAMP? Something like this in your .bash_profile or .profile could do

`alias php='/Applications/MAMP/bin/php/php7.0.22/bin/php -c "/Library/Application Support/appsolute/MAMP PRO/conf/php7.0.22.ini"'`

**Comment by imperator99** [comment]
Hi @invisigoth,

Adding that alias to .bash_profile didn't change the output of `which php` but if I do `php -v` I get 7.0.22 (cli).

Thanks,
Jesse.

**Comment by pandaskii** [comment]
We have bumped PHP version requirement to 7.1

Please raise the ticket again if this issue is still ongoing

**Comment by imperator99** [comment]
Thanks @pandaskii was able to install with no dramas.
