### ISSUE TITLE
Include package.json for NPM install in theme folder

### ISSUE THREAD

**Issue by imperator99** [govCMS/govCMS8-core#3]
Hi,
While trying to debug an issue with the Bootstrap tooltips, I tried to run NPM install so I could use gulp, however there's no package.json to install from. Instead, the required packages are listed in gulpfile.js itself. I think a better way is to add installation instructions to the readme file and keep the gulpfile free of installation instructions.
Additionally, using gulp-compass requires the Compass Ruby gem which isn't obvious at first. Installation instructions for this should also be included in the readme file.
Thanks,
Jesse.

**Comment by imperator99** [comment]
I also had a hell of a time trying to install the Sass gem, apparently because of changes in OSX. [This comment](https://github.com/sass/sass/issues/1768#issuecomment-139297377) helped me fix it.

**Comment by fribibb** [comment]
Change made in https://github.com/govCMS/govCMS8-ui
