### ISSUE TITLE
Remove automatic inclusion of Bootstrap tooltips

### ISSUE THREAD

**Issue by imperator99** [govCMS/govCMS8-core#6]
Hi,
This issue spins out from #5.

Once I turned Bootstrap off, I was still receiving 5 JS errors all from themes/contrib/govcms-ui/js/scripts.js.

The problem was occurring because the theme automatically applies Bootstrap tooltips even if Bootstrap itself is turned off.

Checking whether `tooltip` is a function to `scripts.js` fixes this:

```js
(function ($, Drupal, drupalSettings) {
  'use strict';
  Drupal.behaviors.mybehavior = {
    attach: function (context, settings) {
      // Check if the tooltip function exists.
      if (typeof tooltip == 'function') {
        // Let's use bootstraps title display as it's much nicer!
        $('main.container [title]').each(function() {
          if ($(this).parents('.sf-dump, .kint').length) {
            // Need this to stop it running on our dump/kint commands which breaks expansions
            return;
          }
          $(this).attr('data-toggle', 'tooltip');
          $(this).attr('data-placement', 'top');
        });
        $('[data-toggle="tooltip"]').tooltip();
      }
    }
  };
})(jQuery, Drupal, drupalSettings);
```
When turning off Bootstrap this should also turn off inclusion of the tooltip function.

Cheers,
Jesse.

**Comment by fribibb** [comment]
@imperator99, happy to accept a PR for this one too.
Please make sure to apply the code change to the JS in in src though. Gulp will generate the final file.

**Comment by pandaskii** [comment]
Merged, thanks for contribution
