### ISSUE TITLE
Install error: govcms_install_optional_form

### ISSUE THREAD

**Issue by xtfer** [govCMS/govCMS8-core#9]
I get this at the end of the install process...

```
Drupal\Core\Form\EnforcedResponseException: in Drupal\Core\Form\FormBuilder->buildForm() (line 346 of core/lib/Drupal/Core/Form/FormBuilder.php).
Drupal\Core\Form\FormBuilder->buildForm('govcms_install_optional_form', Object) (Line: 894)
install_get_form('Drupal\govcms\Installer\Form\optionalForm', Array) (Line: 584)
install_run_task(Array, Array) (Line: 540)
install_run_tasks(Array) (Line: 117)
install_drupal(Object) (Line: 44)
Installation tasks

```

**Comment by invisigoth** [comment]
Hi @xtfer 

Thank you very much for reporting this issue. We've fixed it in the latest release and please feel free to give it a try again.

Thank you!

**Comment by invisigoth** [comment]
@Venkata-modgu please test this. Please be sure you install all optional content types (e.g. Event, FOI etc) at the last step of the installation.

**Comment by Venkata-modgu** [comment]
Test passed.
No issues found in installation.
